name: openfold_apptainer

on:
  push:
    paths-ignore:
      - '*.sh'
      - '*.sbatch'
  pull_request:
  schedule:
    - cron: '0 0 * * SUN'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:
  workflow_call:

jobs:
  build_image:
    runs-on: ubuntu-20.04
    strategy:
        fail-fast: false
    steps:
    - name: tag
      run: |
        if [[ ${{ github.ref_name }} ==  main ]]; then
        echo "tag=oras://ghcr.io/${{ github.repository }}/openfold" >> $GITHUB_ENV
        else
        echo "tag=oras://ghcr.io/${{ github.repository }}/openfold_${{ github.ref_name }}" >> $GITHUB_ENV
        fi
    - name: echo-tag
      run: |
        echo ' the apptainer tag is ' "${{ env.tag }}"
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        clean: false
    - name: Install apptainer
      env:
        APP_VER: 1.2.2
      run: |
        sudo apt-get install -y  libfuse2 libseccomp2 zlib1g uidmap squashfs-tools squashfuse fuse2fs fuse-overlayfs fakeroot
        wget -q  https://github.com/apptainer/apptainer/releases/download/v${APP_VER}/apptainer_${APP_VER}_amd64.deb 
        sudo dpkg -i apptainer_${APP_VER}_amd64.deb
        rm apptainer_${APP_VER}_amd64.deb
        which apptainer
        apptainer version
    - name: build an apptainer container
      run: |
        pwd
        ls -l
        apptainer build --fakeroot openfold.simg  Singularity.def
    - name: builddate
      id: build-date
      run: |
        echo "date=$(TZ=America/Los_Angeles date +%Y%m%d_%H%M%S)" >> $GITHUB_ENV
    - name: push to ghcr.io
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | apptainer remote login -u ${{ github.actor }} --password-stdin oras://ghcr.io
        pwd
        ls -l
        apptainer remote list
        apptainer push openfold.simg ${{ env.tag }}:${{ env.date }}
        apptainer push openfold.simg ${{ env.tag }}:latest
    - name: test image with apptainer
      run: |
        apptainer pull -F openfold.sif ${{ env.tag }}:${{ env.date }}
        apptainer exec ${{ env.tag }}:${{ env.date }} ldd /opt/conda/bin/hhsearch || true
        apptainer exec ${{ env.tag }}:${{ env.date }} hhsearch -h || true
        apptainer exec ${{ env.tag }}:${{ env.date }} ptxas -V || true
        apptainer cache list -v
